apiVersion: v1
kind: Service
metadata:
  name: squadlist
spec:
  type: NodePort
  selector:
    app: squadlist
  ports:
  - port: 8080
    nodePort: 32200
    name: squadlist
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: squadlist
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: squadlist
    spec:
      containers:
      - name: squadlist
        image: localhost:5000/squadlist:1.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /opt/squadlist/conf
      volumes:
      - name: config-volume
        configMap:
          name: squadlist-config
