package uk.co.squadlist.web.services;

public enum Permission {

	ADD_MEMBER, VIEW_ADMIN_SCREEN, EDIT_ADMIN_SCREEN, VIEW_MEMBER_DETAILS, EDIT_MEMBER_DETAILS, 
	VIEW_ENTRY_DETAILS, VIEW_SQUAD_ENTRY_DETAILS, VIEW_SQUAD_CONTACT_DETAILS,
	EDIT_OUTING, ADD_OUTING
	
}
